In [22]:
import numpy as np
import pandas as pd

In [23]:
df = pd.DataFrame([[8, 8, 1], [7, 9, 1], [6, 10, 0], [5, 5, 0]], columns=['cgpa', 'profile_score', 'placed'])

In [24]:
df

cgpa  profile_score  placed
0     8              8       1
1     7              9       1
2     6             10       0
3     5              5       0

In [25]:
def initialize_params(layer_dim):
    np.random.seed(3)  
    parameters = {}
    L = len(layer_dim)

    for l in range(1, L):
        parameters['W' + str(l)] = np.ones((layer_dim[l-1], layer_dim[l])) * 0.1
        parameters['b' + str(l)] = np.zeros((layer_dim[l], 1))

    return parameters

In [26]:
def sigmoid(z):
    A = 1 / (1 + np.exp(-z))
    return A

In [27]:
# Calculate output of any given neuron
def forward(A, W, b):
    Z = np.dot(W.T, A) + b
    A = sigmoid(Z)
    return A

In [28]:
def forward_propagation(X, params):
    A = X
    L = len(params) // 2

    for l in range(1, L + 1):
        A_prev = A
        Wl = params['W' + str(l)]
        bl = params['b' + str(l)]

        print(f"A{str(l-1)} : {A_prev}")
        print(f"W{str(l)} : {Wl}")
        print(f"b{str(l)} : {bl}")
        print("--" * 25)

        A = forward(A_prev, Wl, bl)
        print(f"A{str(l)} : {A}")
        print("**" * 25)

    return A, A_prev

In [44]:
def update_parameters(params, Y, y_hat, A1, X):
    params['W2'][0][0] = params['W2'][0][0] + (0.02 * (Y - y_hat) * A1[0][0])
    params['W2'][1][0] = params['W2'][1][0] + (0.02 * (Y - y_hat) * A1[1][0])
    params['b2'][0][0] = params['W2'][1][0] + (0.02 * (Y - y_hat))

    params['W1'][0][0] = params['W1'][0][0] + (0.02 * (Y - y_hat) * params['W2'][0][0] * A1[0][0] * (1 - A1[0][0]) * X[0][0])
    params['W1'][0][0] = params['W1'][0][1] + (0.02 * (Y - y_hat) * params['W2'][0][0] * A1[0][0] * (1 - A1[0][0]) * X[1][0])
    params['b1'][0][0] = params['b1'][0][0] + (0.02 * (Y - y_hat) * params['W2'][0][0] * A1[0][0] * (1 - A1[0][0]))

    params['W1'][1][0] = params['W1'][1][0] + (0.02 * (Y - y_hat) * params['W2'][1][0] * A1[1][0] * (1 - A1[1][0]) * X[0][0])
    params['W1'][1][1] = params['W1'][1][1] + (0.02 * (Y - y_hat) * params['W2'][1][0] * A1[1][0] * (1 - A1[1][0]) * X[1][0])
    params['b1'][1][0] = params['b1'][1][0] + (0.02 * (Y - y_hat) * params['W2'][1][0] * A1[1][0] * (1 - A1[1][0]))

### First row

In [30]:
X = df.iloc[0,:-1].values.reshape(2, 1)
Y = df.iloc[0,-1]

network_structure = [2, 2, 1]

params = initialize_params(network_structure)
y_hat, A_prev = forward_propagation(X, params)
y_hat = y_hat[0][0]
update_parameters(params, Y, y_hat, A_prev, X)
print(f"\n\n-----------------------------------------------------------------------------------------")
print(f"|\tHere A0 is [8, 8](cgpa, profile_score), A1 is [O11, O12], A2 is [O21](y_hat)\t|")
print(f"-----------------------------------------------------------------------------------------\n\n")
print(f"Loss {-Y * np.log(y_hat) - (1 - Y) * np.log(1 - y_hat)}")

A0 : [[8]
 [8]]
W1 : [[0.1 0.1]
 [0.1 0.1]]
b1 : [[0.]
 [0.]]
--------------------------------------------------
A1 : [[0.83201839]
 [0.83201839]]
**************************************************
A1 : [[0.83201839]
 [0.83201839]]
W2 : [[0.1]
 [0.1]]
b2 : [[0.]]
--------------------------------------------------
A2 : [[0.54150519]]
**************************************************


-----------------------------------------------------------------------------------------
|	Here A0 is [8, 8](cgpa, profile_score), A1 is [O11, O12], A2 is [O21](y_hat)	|
-----------------------------------------------------------------------------------------


Loss 0.613402628898913


In [31]:
params

{'W1': array([[0.10000513, 0.1       ],
        [0.10000513, 0.10000513]]),
 'b1': array([[6.41054186e-07],
        [6.41054186e-07]]),
 'W2': array([[0.10003815],
        [0.10003815]]),
 'b2': array([[0.100084]])}

### Second data-point

In [32]:
X = df.iloc[1,:-1].values.reshape(2, 1)
Y = df.iloc[1,-1]

network_structure = [2, 2, 1]

params = initialize_params(network_structure)
y_hat, A_prev = forward_propagation(X, params)
y_hat = y_hat[0][0]
update_parameters(params, Y, y_hat, A_prev, X)
print(f"\n\n-----------------------------------------------------------------------------------------")
print(f"|\tHere A0 is [7, 9](cgpa, profile_score), A1 is [O11, O12], A2 is [O21](y_hat)\t|")
print(f"-----------------------------------------------------------------------------------------\n\n")
print(f"Loss {-Y * np.log(y_hat) - (1 - Y) * np.log(1 - y_hat)}")

A0 : [[7]
 [9]]
W1 : [[0.1 0.1]
 [0.1 0.1]]
b1 : [[0.]
 [0.]]
--------------------------------------------------
A1 : [[0.83201839]
 [0.83201839]]
**************************************************
A1 : [[0.83201839]
 [0.83201839]]
W2 : [[0.1]
 [0.1]]
b2 : [[0.]]
--------------------------------------------------
A2 : [[0.54150519]]
**************************************************


-----------------------------------------------------------------------------------------
|	Here A0 is [7, 9](cgpa, profile_score), A1 is [O11, O12], A2 is [O21](y_hat)	|
-----------------------------------------------------------------------------------------


Loss 0.613402628898913


### Third data-point

In [33]:
X = df.iloc[2,:-1].values.reshape(2, 1)
Y = df.iloc[2,-1]

network_structure = [2, 2, 1]

params = initialize_params(network_structure)
y_hat, A_prev = forward_propagation(X, params)
y_hat = y_hat[0][0]
update_parameters(params, Y, y_hat, A_prev, X)
print(f"\n\n-----------------------------------------------------------------------------------------")
print(f"|\tHere A0 is [6, 10](cgpa, profile_score), A1 is [O11, O12], A2 is [O21](y_hat)\t|")
print(f"-----------------------------------------------------------------------------------------\n\n")
print(f"Loss {-Y * np.log(y_hat) - (1 - Y) * np.log(1 - y_hat)}")

A0 : [[ 6]
 [10]]
W1 : [[0.1 0.1]
 [0.1 0.1]]
b1 : [[0.]
 [0.]]
--------------------------------------------------
A1 : [[0.83201839]
 [0.83201839]]
**************************************************
A1 : [[0.83201839]
 [0.83201839]]
W2 : [[0.1]
 [0.1]]
b2 : [[0.]]
--------------------------------------------------
A2 : [[0.54150519]]
**************************************************


-----------------------------------------------------------------------------------------
|	Here A0 is [6, 10](cgpa, profile_score), A1 is [O11, O12], A2 is [O21](y_hat)	|
-----------------------------------------------------------------------------------------


Loss 0.7798063059256977


### Fourth data-point

In [34]:
X = df.iloc[3,:-1].values.reshape(2, 1)
Y = df.iloc[3,-1]

network_structure = [2, 2, 1]

params = initialize_params(network_structure)
y_hat, A_prev = forward_propagation(X, params)
y_hat = y_hat[0][0]
update_parameters(params, Y, y_hat, A_prev, X)
print(f"\n\n-----------------------------------------------------------------------------------------")
print(f"|\tHere A0 is [5, 5](cgpa, profile_score), A1 is [O11, O12], A2 is [O21](y_hat)\t|")
print(f"-----------------------------------------------------------------------------------------\n\n")
print(f"Loss {-Y * np.log(y_hat) - (1 - Y) * np.log(1 - y_hat)}")

A0 : [[5]
 [5]]
W1 : [[0.1 0.1]
 [0.1 0.1]]
b1 : [[0.]
 [0.]]
--------------------------------------------------
A1 : [[0.73105858]
 [0.73105858]]
**************************************************
A1 : [[0.73105858]
 [0.73105858]]
W2 : [[0.1]
 [0.1]]
b2 : [[0.]]
--------------------------------------------------
A2 : [[0.53648795]]
**************************************************


-----------------------------------------------------------------------------------------
|	Here A0 is [5, 5](cgpa, profile_score), A1 is [O11, O12], A2 is [O21](y_hat)	|
-----------------------------------------------------------------------------------------


Loss 0.768922894759937


In [35]:
def forward_prop(X, params):
    A = X
    L = len(params) // 2

    for l in range(1, L + 1):
        A_prev = A
        Wl = params['W' + str(l)]
        bl = params['b' + str(l)]

        A = forward(A_prev, Wl, bl)

    return A, A_prev

In [45]:
params = initialize_params(network_structure)
epochs = 100

for i in range(epochs):
    
    loss = []
    
    for j in range(X.shape[0]):
        
        X = df.iloc[j,:-1].values.reshape(2, 1)
        Y = df.iloc[j,-1]

        y_hat, A_previous = forward_prop(X, params)
        y_hat = y_hat[0][0]

        update_parameters(params, Y, y_hat, A_previous, X)

        loss.append((-Y * np.log(y_hat) - (1 - Y) * np.log(1 - y_hat)))

    print(f"At {i + 1} epoch, loss = {np.array(loss).mean()}")

At 1 epoch, loss = 0.5846636507416068
At 2 epoch, loss = 0.5440218915708116
At 3 epoch, loss = 0.5283082977874415
At 4 epoch, loss = 0.5131404516232378
At 5 epoch, loss = 0.49849705343666784
At 6 epoch, loss = 0.48435962245363395
At 7 epoch, loss = 0.47071140574746606
At 8 epoch, loss = 0.45753696372037356
At 9 epoch, loss = 0.44482183038729606
At 10 epoch, loss = 0.4325522425029809
At 11 epoch, loss = 0.42071493028919477
At 12 epoch, loss = 0.40929696181128955
At 13 epoch, loss = 0.39828563285310514
At 14 epoch, loss = 0.3876683943460917
At 15 epoch, loss = 0.3774328099181526
At 16 epoch, loss = 0.3675665368405723
At 17 epoch, loss = 0.3580573244796984
At 18 epoch, loss = 0.3488930252312734
At 19 epoch, loss = 0.3400616137737159
At 20 epoch, loss = 0.3315512112825512
At 21 epoch, loss = 0.3233501119763046
At 22 epoch, loss = 0.3154468100009793
At 23 epoch, loss = 0.3078300252014601
At 24 epoch, loss = 0.30048872677605953
At 25 epoch, loss = 0.2934121541716655
At 26 epoch, loss = 0.286

<hr>

<h2 style="text-align: center;">Using Keras</h2>

<hr>

In [46]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [47]:
model = Sequential()

model.add(Dense(2, activation='sigmoid', input_dim=2))
model.add(Dense(1, activation='sigmoid'))

C:\Users\Parth\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\core\dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [48]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 2)                   │               6 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 1)                   │               3 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [49]:
# As above shows, keras has initialized weights in his own way, but we want to initialize weights in our own way
new_weights = [np.array([[0.1, 0.1], 
                         [0.1, 0.1]], dtype=np.float32),
              np.array([0., 0.], dtype=np.float32),
              np.array([[0.1],
                        [0.1]], dtype=np.float32),
              np.array([0.], dtype=np.float32)]

In [50]:
model.set_weights(new_weights)

In [51]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [60]:
optimizer = keras.optimizers.Adam(learning_rate=0.1)
model.compile(loss='binary_crossentropy', optimizer=optimizer)

In [61]:
model.fit(df.iloc[:,:-1].values, df['placed'].values, epochs=150, verbose=1, batch_size=1)

Epoch 1/150
4/4 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.6798
Epoch 2/150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.4132
Epoch 3/150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.5500
Epoch 4/150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.5659
Epoch 5/150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.5843
Epoch 6/150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.5227
Epoch 7/150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.4978
Epoch 8/150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.5919
Epoch 9/150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.5677
Epoch 10/150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.4849
Epoch 11/150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.4734
Epoch 12/150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.4736
Epoch 13/150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.4933
Epoch 14/150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.4498
Epoch 15/150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.3513
Epoch 16/150
4/4 ━━