In [70]:
import numpy as np
import pandas as pd

In [71]:
df = pd.DataFrame([[8, 8, 4], [7, 9, 5], [6, 10, 6], [5, 12, 7]], columns=['cgpa', 'profile_score', 'lpa'])

In [72]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [73]:
def initialize_params(layer_dim):
    np.random.seed(3)  
    parameters = {}
    L = len(layer_dim)

    for l in range(1, L):
        parameters['W' + str(l)] = np.ones((layer_dim[l-1], layer_dim[l])) * 0.1
        parameters['b' + str(l)] = np.zeros((layer_dim[l], 1))

    return parameters

In [74]:
initialize_params([2, 2, 1])

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [75]:
# Calculate output of any given neuron
def forward(A, W, b):
    Z = np.dot(W.T, A) + b
    return Z

In [76]:
def forward_propagation(X, params):
    A = X
    L = len(params) // 2

    for l in range(1, L + 1):
        A_prev = A
        Wl = params['W' + str(l)]
        bl = params['b' + str(l)]

        print(f"A{str(l-1)} : {A_prev}")
        print(f"W{str(l)} : {Wl}")
        print(f"b{str(l)} : {bl}")
        print("--" * 25)

        A = forward(A_prev, Wl, bl)
        print(f"A{str(l)} : {A}")
        print("**" * 25)

    return A, A_prev

---
### Selecting first row 

In [77]:
X = df.iloc[0,:-1].values.reshape(2, 1)
Y = df.iloc[0,-1]

In [78]:
network_structure = [2, 2, 1]
parameters = initialize_params(network_structure)

In [79]:
y_hat, A_previous = forward_propagation(X, parameters)
print(f"\n\n-----------------------------------------------------------------------------------------")
print(f"|\tHere A0 is [8, 8](cgpa, profile_score), A1 is [O11, O12], A2 is [O21](y_hat)\t|")
print(f"-----------------------------------------------------------------------------------------\n\n")

A0 : [[8]
 [8]]
W1 : [[0.1 0.1]
 [0.1 0.1]]
b1 : [[0.]
 [0.]]
--------------------------------------------------
A1 : [[1.6]
 [1.6]]
**************************************************
A1 : [[1.6]
 [1.6]]
W2 : [[0.1]
 [0.1]]
b2 : [[0.]]
--------------------------------------------------
A2 : [[0.32]]
**************************************************


-----------------------------------------------------------------------------------------
|	Here A0 is [8, 8](cgpa, profile_score), A1 is [O11, O12], A2 is [O21](y_hat)	|
-----------------------------------------------------------------------------------------




In [80]:
y_hat = y_hat[0][0]

loss = (Y - y_hat) ** 2

In [81]:
loss

np.float64(13.542399999999997)

In [82]:
def update_parameters(params, Y, y_hat, A1, X):
    params['W2'][0][0] = params['W2'][0][0] + (0.001 * 2 * (Y - y_hat) * A1[0][0])
    params['W2'][1][0] = params['W2'][1][0] + (0.001 * 2 * (Y - y_hat) * A1[1][0])
    params['b2'][0][0] = params['W2'][1][0] + (0.001 * 2 * (Y - y_hat))

    params['W1'][0][0] = params['W1'][0][0] + (0.001 * 2 * (Y - y_hat) * params['W2'][0][0] * X[0][0])
    params['W1'][0][0] = params['W1'][0][1] + (0.001 * 2 * (Y - y_hat) * params['W2'][0][0] * X[1][0])
    params['b1'][0][0] = params['b1'][0][0] + (0.001 * 2 * (Y - y_hat) * params['W2'][0][0])

    params['W1'][1][0] = params['W1'][1][0] + (0.001 * 2 * (Y - y_hat) * params['W2'][1][0] * X[0][0])
    params['W1'][1][1] = params['W1'][1][1] + (0.001 * 2 * (Y - y_hat) * params['W2'][1][0] * X[1][0])
    params['b1'][1][0] = params['b1'][1][0] + (0.001 * 2 * (Y - y_hat) * params['W2'][1][0])

In [83]:
y_hat, A_previous

(np.float64(0.32000000000000006),
 array([[1.6],
        [1.6]]))

In [84]:
update_parameters(parameters, Y, y_hat, A_previous, X)

In [85]:
parameters

{'W1': array([[0.10658137, 0.1       ],
        [0.10658137, 0.10658137]]),
 'b1': array([[0.00082267],
        [0.00082267]]),
 'W2': array([[0.111776],
        [0.111776]]),
 'b2': array([[0.119136]])}

---
### Selecting second row

In [86]:
X = df.iloc[1,:-1].values.reshape(2, 1)
Y = df.iloc[1,-1]

In [87]:
y_hat, A_previous = forward_propagation(X, parameters)
y_hat = y_hat[0][0]
print(f"\n\n-----------------------------------------------------------------------------------------")
print(f"|\tHere A0 is [7, 9](cgpa, profile_score), A1 is [O11, O12], A2 is [O21](y_hat)\t|")
print(f"-----------------------------------------------------------------------------------------\n\n")

A0 : [[7]
 [9]]
W1 : [[0.10658137 0.1       ]
 [0.10658137 0.10658137]]
b1 : [[0.00082267]
 [0.00082267]]
--------------------------------------------------
A1 : [[1.70612461]
 [1.66005501]]
**************************************************
A1 : [[1.70612461]
 [1.66005501]]
W2 : [[0.111776]
 [0.111776]]
b2 : [[0.119136]]
--------------------------------------------------
A2 : [[0.49539409]]
**************************************************


-----------------------------------------------------------------------------------------
|	Here A0 is [7, 9](cgpa, profile_score), A1 is [O11, O12], A2 is [O21](y_hat)	|
-----------------------------------------------------------------------------------------




In [88]:
update_parameters(parameters, Y, y_hat, A_previous, X)

In [89]:
parameters

{'W1': array([[0.11030944, 0.1       ],
        [0.11457365, 0.11685715]]),
 'b1': array([[0.00196816],
        [0.00196442]]),
 'W2': array([[0.12714684],
        [0.12673179]]),
 'b2': array([[0.135741]])}

---
### Selecting third row

In [90]:
X = df.iloc[2,:-1].values.reshape(2, 1)
Y = df.iloc[2,-1]

In [91]:
y_hat, A_previous = forward_propagation(X, parameters)
y_hat = y_hat[0][0]
print(f"\n\n-----------------------------------------------------------------------------------------")
print(f"|\tHere A0 is [7, 9](cgpa, profile_score), A1 is [O11, O12], A2 is [O21](y_hat)\t|")
print(f"-----------------------------------------------------------------------------------------\n\n")

A0 : [[ 6]
 [10]]
W1 : [[0.11030944 0.1       ]
 [0.11457365 0.11685715]]
b1 : [[0.00196816]
 [0.00196442]]
--------------------------------------------------
A1 : [[1.80956123]
 [1.77053595]]
**************************************************
A1 : [[1.80956123]
 [1.77053595]]
W2 : [[0.12714684]
 [0.12673179]]
b2 : [[0.135741]]
--------------------------------------------------
A2 : [[0.59020417]]
**************************************************


-----------------------------------------------------------------------------------------
|	Here A0 is [7, 9](cgpa, profile_score), A1 is [O11, O12], A2 is [O21](y_hat)	|
-----------------------------------------------------------------------------------------




In [92]:
update_parameters(parameters, Y, y_hat, A_previous, X)

In [93]:
parameters

{'W1': array([[0.11587511, 0.1       ],
        [0.12404435, 0.13264167]]),
 'b1': array([[0.00355567],
        [0.00354288]]),
 'W2': array([[0.14672555],
        [0.14588826]]),
 'b2': array([[0.15670785]])}

---
### Selecting fourth row

In [94]:
X = df.iloc[3,:-1].values.reshape(2, 1)
Y = df.iloc[3,-1]

In [95]:
y_hat, A_previous = forward_propagation(X, parameters)
y_hat = y_hat[0][0]
print(f"\n\n-----------------------------------------------------------------------------------------")
print(f"|\tHere A0 is [7, 9](cgpa, profile_score), A1 is [O11, O12], A2 is [O21](y_hat)\t|")
print(f"-----------------------------------------------------------------------------------------\n\n")

A0 : [[ 5]
 [12]]
W1 : [[0.11587511 0.1       ]
 [0.12404435 0.13264167]]
b1 : [[0.00355567]
 [0.00354288]]
--------------------------------------------------
A1 : [[2.07146345]
 [2.09524288]]
**************************************************
A1 : [[2.07146345]
 [2.09524288]]
W2 : [[0.14672555]
 [0.14588826]]
b2 : [[0.15670785]]
--------------------------------------------------
A2 : [[0.76631582]]
**************************************************


-----------------------------------------------------------------------------------------
|	Here A0 is [7, 9](cgpa, profile_score), A1 is [O11, O12], A2 is [O21](y_hat)	|
-----------------------------------------------------------------------------------------




In [96]:
update_parameters(parameters, Y, y_hat, A_previous, X)

In [97]:
parameters

{'W1': array([[0.12581512, 0.1       ],
        [0.13476694, 0.15837588]]),
 'b1': array([[0.00570693],
        [0.00568739]]),
 'W2': array([[0.17255125],
        [0.17201043]]),
 'b2': array([[0.1844778]])}

---

## Using epochs 

In [101]:
def forward_prop(X, params):
    A = X
    L = len(params) // 2

    for l in range(1, L + 1):
        A_prev = A
        Wl = params['W' + str(l)]
        bl = params['b' + str(l)]

        A = forward(A_prev, Wl, bl)

    return A, A_prev

In [104]:
params = initialize_params(network_structure)
epochs = 10

for i in range(epochs):
    
    loss = []
    
    for j in range(X.shape[0]):
        
        X = df.iloc[j,:-1].values.reshape(2, 1)
        Y = df.iloc[j,-1]

        y_hat, A_previous = forward_prop(X, params)
        y_hat = y_hat[0][0]

        update_parameters(params, Y, y_hat, A_previous, X)

        loss.append((Y - y_hat) ** 2)

    print(f"At {i + 1} epoch, loss = {np.array(loss).mean()}")

At 1 epoch, loss = 16.91693719042418
At 2 epoch, loss = 15.263278522710081
At 3 epoch, loss = 13.861415441962475
At 4 epoch, loss = 12.297592380996697
At 5 epoch, loss = 10.606878486836806
At 6 epoch, loss = 8.852720819671084
At 7 epoch, loss = 7.121114621384424
At 8 epoch, loss = 5.506010162155689
At 9 epoch, loss = 4.08933855731013
At 10 epoch, loss = 2.923189609412688


In [105]:
params

{'W1': array([[0.11404206, 0.1       ],
        [0.30284014, 0.33535475]]),
 'b1': array([[0.02749546],
        [0.02738718]]),
 'W2': array([[0.38058758],
        [0.38286948]]),
 'b2': array([[0.38696901]])}

<hr>

<h2 style="text-align: center;">Using Keras</h2>

<hr>

In [106]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [108]:
model = Sequential()

model.add(Dense(2, activation='linear', input_dim=2))
model.add(Dense(1, activation='linear'))

C:\Users\Parth\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\core\dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [109]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 2)                   │               6 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 1)                   │               3 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [110]:
model.get_weights()

[array([[-0.6460879 , -0.59826964],
        [-0.33937663,  0.83501256]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.06464183],
        [1.1060003 ]], dtype=float32),
 array([0.], dtype=float32)]

In [111]:
# As above shows, keras has initialized weights in his own way, but we want to initialize weights in our own way
new_weights = [np.array([[0.1, 0.1], 
                         [0.1, 0.1]], dtype=np.float32),
              np.array([0., 0.], dtype=np.float32),
              np.array([[0.1],
                        [0.1]], dtype=np.float32),
              np.array([0.], dtype=np.float32)]

In [112]:
model.set_weights(new_weights)

In [113]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [116]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error', optimizer=optimizer)

In [117]:
model.fit(df.iloc[:,:-1].values, df['lpa'].values, epochs=75, verbose=1, batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 4.8128  
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 4.5304 
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 3.8146 
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 6.6691  
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 5.4906
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 4.3749 
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5.3266 
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 4.4405 
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4.5111 
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.7898 
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.5546
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 3.8903 
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 2.5499 
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 3.4105 
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 3.0284 
Epoch 16/75
4/4 ━━━━━━━━━━━━━━━━

In [118]:
model.get_weights()

[array([[0.36987755, 0.36987755],
        [0.40488473, 0.40488473]], dtype=float32),
 array([0.2940629, 0.2940629], dtype=float32),
 array([[0.3968211],
        [0.3968211]], dtype=float32),
 array([0.24750356], dtype=float32)]